"""Remove email reminder tables

Revision ID: 92e041b88016
Revises: 5b89fecfa20b
Create Date: 2025-12-23 09:52:43.102532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92e041b88016'
down_revision = '5b89fecfa20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_history')
    op.drop_table('guest_reminder_preference')
    op.drop_table('reminder_batch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_batch',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_guests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sent_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('failed_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skipped_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('executed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('days_before_deadline', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reminder_batch_pkey'))
    )
    op.create_table('guest_reminder_preference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opt_out', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('preferred_language', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('max_reminders', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_sent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_reminder_sent', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('guest_reminder_preference_guest_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('guest_reminder_preference_pkey')),
    sa.UniqueConstraint('guest_id', name=op.f('guest_reminder_preference_guest_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('reminder_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reminder_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email_sent_to', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('email_subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], name=op.f('reminder_history_guest_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reminder_history_pkey'))
    )
    # ### end Alembic commands ###
