"""Add preboda fields to Guest and RSVP

Revision ID: ab830794c6ea
Revises: cc6c897496c2
Create Date: 2026-01-08 21:33:52.298517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab830794c6ea'
down_revision = 'cc6c897496c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preboda_invited', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preboda_attending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.drop_column('preboda_attending')

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('preboda_invited')

    # ### end Alembic commands ###