"""Add needs_menu field to AdditionalGuest

Revision ID: b0724c4a094d
Revises: de0f1b80d892
Create Date: 2026-01-21 09:24:19.586993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0724c4a094d'
down_revision = 'de0f1b80d892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_menu', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_guest', schema=None) as batch_op:
        batch_op.drop_column('needs_menu')

    # ### end Alembic commands ###
