"""Add personal_message to guest

Revision ID: cc6c897496c2
Revises: 92e041b88016
Create Date: 2025-12-30 21:07:52.675415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6c897496c2'
down_revision = '92e041b88016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_message', sa.Text(), nullable=True))
        batch_op.drop_column('has_plus_one')
        batch_op.drop_column('is_family')
        batch_op.drop_column('email')
        batch_op.drop_column('plus_one_used')

    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.drop_column('plus_one_name')
        batch_op.drop_column('transport_to_church')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_to_church', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('plus_one_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plus_one_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_family', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_plus_one', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('personal_message')

    # ### end Alembic commands ###
