"""Add surname to Guest model

Revision ID: de0f1b80d892
Revises: ab830794c6ea
Create Date: 2026-01-17 18:05:56.211840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0f1b80d892'
down_revision = 'ab830794c6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
