"""installing requirements and first migration 2

Revision ID: fad6002ee827
Revises: 
Create Date: 2025-03-10 20:37:26.370764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad6002ee827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('language_preference', sa.String(length=2), nullable=True),
    sa.Column('has_plus_one', sa.Boolean(), nullable=True),
    sa.Column('plus_one_used', sa.Boolean(), nullable=True),
    sa.Column('is_family', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('is_attending', sa.Boolean(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('adults_count', sa.Integer(), nullable=True),
    sa.Column('children_count', sa.Integer(), nullable=True),
    sa.Column('plus_one_name', sa.String(length=120), nullable=True),
    sa.Column('hotel_name', sa.String(length=200), nullable=True),
    sa.Column('transport_to_church', sa.Boolean(), nullable=True),
    sa.Column('transport_to_reception', sa.Boolean(), nullable=True),
    sa.Column('transport_to_hotel', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('cancellation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rsvp_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_child', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rsvp_id'], ['rsvp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guest_allergen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rsvp_id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=120), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=True),
    sa.Column('custom_allergen', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.id'], ),
    sa.ForeignKeyConstraint(['rsvp_id'], ['rsvp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_allergen')
    op.drop_table('additional_guest')
    op.drop_table('rsvp')
    op.drop_table('guest')
    op.drop_table('allergen')
    # ### end Alembic commands ###
